---
- hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

- import_playbook: jenkins_setup.yml
- import_playbook: api_setup.yml
