---
- name: Configure FTTH Fault Detection Environment
  hosts: all
  become: yes
  gather_facts: yes
  
  vars_files:
    - vars/main.yml
  
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
    
    - name: Install common dependencies
      package:
        name:
          - python3
          - python3-pip
          - git
          - unzip
          - curl
          - wget
          - ca-certificates
          - gnupg
          - lsb-release
        state: present
  
  roles:
    - common
    - { role: docker, when: "'api_servers' in group_names or 'jenkins_servers' in group_names" }
    - { role: aws_cli, when: "'api_servers' in group_names or 'jenkins_servers' in group_names or 'training_servers' in group_names" }
    - { role: jenkins, when: "'jenkins_servers' in group_names" }
    - { role: api, when: "'api_servers' in group_names" }
    - { role: training, when: "'training_servers' in group_names" }
